### ISSUE TITLE
what should be in config.json

### ISSUE THREAD

**Issue by Botmakingisafunsport** [TerrificTable/YouTube-and-TikTok--View-Bot#2]

**Comment by TerrificTable** [comment]
basicaly if you start the program for the first time it asks you for the path to a chromedriver.exe file, thats what is saved in the config.json file

**Comment by axen1** [comment]
dude i couldn't do it can you help me

**Comment by TerrificTable** [comment]
> dude i couldn't do it can you help me

With what exactly? 
Running the program? Install Python 3.9.7 and execute this command: "python3 -m pip install -r requirements.txt" if you use Linux, if you use Windows: "python -m pip install -r requirements.txt"
